spring:
  datasource:
    username: ju22user
    password: ju22pass
    url: jdbc:postgresql://93.175.204.87:5432/postgres?currentSchema=romantsev
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false