spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=romantsev
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false