spring:
  application:
    name: nasa-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
